In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy as sp
import sklearn as sk

In [2]:
x = np.array([49, 58, 75, 110, 112, 132, 151, 276, 281, 362])

In [4]:
stats = (x>200).sum()
stats

3

In [6]:
sp.stats.binom.cdf(stats,len(x),0.5)*2

0.34375

In [8]:
res = sp.stats.wilcoxon(x-200)
res.statistic, res.pvalue

(17.0, 0.322265625)

In [9]:
sp.stats.wilcoxon

<function scipy.stats._morestats.wilcoxon(x, y=None, zero_method='wilcox', correction=False, alternative='two-sided', method='auto', *, axis=0, nan_policy='propagate', keepdims=False)>

In [10]:
surv_data = np.array( [49, 58, 75, 110, 112, 132, 151, 276, 281, 362] )
surv_data
surv_data.mean()

160.6

In [12]:

exp_surv = 200
sp.stats.wilcoxon(surv_data - exp_surv)

WilcoxonResult(statistic=17.0, pvalue=0.322265625)

In [14]:
virgin_forest = np.array([22,22,15,13,19,19,18,20,21,13,13,15])
not_virgin_forest = np.array([17,18,18,15,12,4,14,15,10])
U1, p = sp.stats.mannwhitneyu(virgin_forest, not_virgin_forest,alternative = 'greater')
print(U1, p)

81.0 0.02900499272087373


In [18]:
data = pd.read_csv('chalinger.txt',sep='\t')
data

Unnamed: 0  Temperature  Incident
0    Apr12.81         18.9         0
1    Nov12.81         21.1         1
2    Mar22.82         20.6         0
3    Nov11.82         20.0         0
4    Apr04.83         19.4         0
5    Jun18.83         22.2         0
6    Aug30.83         22.8         0
7    Nov28.83         21.1         0
8    Feb03.84         13.9         1
9    Apr06.84         17.2         1
10   Aug30.84         21.1         1
11   Oct05.84         25.6         0
12   Nov08.84         19.4         0
13   Jan24.85         11.7         1
14   Apr12.85         19.4         0
15   Apr29.85         23.9         0
16   Jun17.85         21.1         0
17   Jul29.85         27.2         0
18   Aug27.85         24.4         0
19   Oct03.85         26.1         0
20   Oct30.85         23.9         1
21   Nov26.85         24.4         0
22   Jan12.86         14.4         1

In [45]:
def get_bootstrap_samples(data, n_samples):
    indices = np.random.randint(0, len(data), (n_samples, len(data)))
    samples = data[indices]
    return samples
def stat_intervals(stat, alpha):
    boundaries = np.percentile(stat, [100 * alpha / 2., 100 * (1 - alpha / 2.)])
    return boundaries

In [46]:
np.random.seed(0)
samples = get_bootstrap_samples(data.to_numpy(),10)
norm_mask = samples[:,:,2]==0
ecident_mask = samples[:,:,2]==1
diferance_means = samples[norm_mask][:,1].mean() - samples[ecident_mask][:,1].mean()
diferance_means

4.711878765060245

In [47]:
stat_intervals(1,0.05)

array([1., 1.])

In [49]:
life_values = data[data.Incident == 0].Temperature.values
death_values = data[data.Incident == 1].Temperature.values

In [50]:
life_values

array([18.9, 20.6, 20. , 19.4, 22.2, 22.8, 21.1, 25.6, 19.4, 19.4, 23.9,
       21.1, 27.2, 24.4, 26.1, 24.4])

In [51]:
death_values

array([21.1, 13.9, 17.2, 21.1, 11.7, 23.9, 14.4])

In [60]:
life_values.mean() - death_values.mean()

4.666964285714283

In [52]:
samples[norm_mask][:,1]

array([19.4, 23.9, 24.4, 18.9, 20.0, 20.0, 21.1, 26.1, 24.4, 24.4, 19.4,
       22.8, 19.4, 22.8, 21.1, 19.4, 27.2, 22.2, 26.1, 21.1, 26.1, 22.2,
       23.9, 23.9, 18.9, 24.4, 20.0, 27.2, 26.1, 26.1, 26.1, 19.4, 21.1,
       18.9, 18.9, 20.0, 25.6, 24.4, 20.6, 18.9, 18.9, 19.4, 24.4, 22.2,
       22.8, 27.2, 23.9, 19.4, 21.1, 20.0, 22.8, 25.6, 19.4, 24.4, 18.9,
       19.4, 20.0, 24.4, 19.4, 25.6, 19.4, 22.8, 19.4, 23.9, 20.0, 19.4,
       19.4, 19.4, 23.9, 20.0, 23.9, 24.4, 24.4, 21.1, 27.2, 22.2, 20.0,
       18.9, 22.2, 18.9, 27.2, 24.4, 19.4, 20.6, 21.1, 20.0, 20.6, 21.1,
       21.1, 24.4, 18.9, 24.4, 25.6, 20.6, 20.6, 20.0, 20.0, 24.4, 19.4,
       20.0, 27.2, 24.4, 19.4, 19.4, 25.6, 25.6, 20.6, 26.1, 21.1, 18.9,
       18.9, 22.8, 26.1, 19.4, 26.1, 20.6, 20.0, 20.6, 25.6, 21.1, 26.1,
       20.6, 20.0, 19.4, 19.4, 18.9, 19.4, 20.0, 25.6, 25.6, 21.1, 24.4,
       19.4, 21.1, 24.4, 26.1, 18.9, 19.4, 22.8, 24.4, 21.1, 23.9, 24.4,
       23.9, 25.6, 22.8, 23.9, 19.4, 20.0, 24.4, 23

In [54]:
data[data.Incident == 0].Temperature.values

array([18.9, 20.6, 20. , 19.4, 22.2, 22.8, 21.1, 25.6, 19.4, 19.4, 23.9,
       21.1, 27.2, 24.4, 26.1, 24.4])

In [56]:
np.random.seed(0)

life_scores = np.array(list(map(np.mean, get_bootstrap_samples(life_values, 1000))))
death_scores = np.array(list(map(np.mean, get_bootstrap_samples(death_values, 1000))))
delta_scores = life_scores -  death_scores

print("95% confidence interval for the life temperature:",  stat_intervals(life_scores, 0.05))
print("95% confidence interval for the death temperature:",  stat_intervals(death_scores, 0.05))
print("95% confidence interval for the delta temperature:",  stat_intervals(delta_scores, 0.05))

95% confidence interval for the life temperature: [21.06875  23.575625]
95% confidence interval for the death temperature: [14.5125     20.71607143]
95% confidence interval for the delta temperature: [1.42299107 7.93861607]


In [62]:
import itertools
def permutation_t_stat_ind(sample1, sample2):
    return np.mean(sample1) - np.mean(sample2)
def get_random_combinations(n1, n2, max_combinations):
    index = list(range(n1 + n2))
    indices = set([tuple(index)])
    for i in range(max_combinations - 1):
        np.random.shuffle(index)
        indices.add(tuple(index))
    return [(index[:n1], index[n1:]) for index in indices]
def permutation_zero_dist_ind(sample1, sample2, max_combinations = None):
    joined_sample = np.hstack((sample1, sample2))
    n1 = len(sample1)
    n = len(joined_sample)
    
    if max_combinations:
        indices = get_random_combinations(n1, len(sample2), max_combinations)
    else:
        indices = [(list(index), list(filter(lambda i: i not in index, range(n)))) \
                    for index in itertools.combinations(range(n), n1)]
    
    distr = [joined_sample[list(i[0])].mean() - joined_sample[list(i[1])].mean() \
             for i in indices]
    return distr

def permutation_test(sample, mean, max_permutations = None, alternative = 'two-sided'):
    if alternative not in ('two-sided', 'less', 'greater'):
        raise ValueError("alternative not recognized\n"
                         "should be 'two-sided', 'less' or 'greater'")
    
    t_stat = permutation_t_stat_ind(sample, mean)
    
    zero_distr = permutation_zero_dist_ind(sample, mean, max_permutations)
    
    if alternative == 'two-sided':
        return sum([1. if abs(x) >= abs(t_stat) else 0. for x in zero_distr]) / len(zero_distr)
    
    if alternative == 'less':
        return sum([1. if x <= t_stat else 0. for x in zero_distr]) / len(zero_distr)

    if alternative == 'greater':
        return sum([1. if x >= t_stat else 0. for x in zero_distr]) / len(zero_distr)


np.random.seed(0)


In [65]:
np.random.seed(0)
permutation_test(death_values, life_values, max_permutations = 10000)

0.0057

In [58]:
delta_scores

array([ 3.79375   ,  4.06160714,  1.97589286,  5.02142857,  2.06071429,
        3.5625    ,  5.93928571,  4.05982143,  6.99196429,  3.62678571,
        4.00267857,  3.61071429,  3.62232143,  5.31160714,  5.76785714,
        4.52410714,  2.18125   ,  4.82589286,  6.13035714,  3.07857143,
        4.69821429,  4.15446429,  1.44642857,  4.12946429,  4.83214286,
        3.65625   ,  3.66875   ,  5.51160714,  2.33571429,  2.72857143,
        1.04464286,  7.4625    ,  4.14285714,  0.98839286,  5.87053571,
        3.85803571,  2.67410714,  3.26339286,  6.28303571,  3.47321429,
        4.79017857,  4.85803571,  4.21071429,  4.08214286,  1.59017857,
        5.73125   ,  5.93392857,  4.28214286,  3.65178571,  4.03928571,
        3.69017857,  3.63392857,  6.71875   ,  5.35535714,  4.41696429,
        6.43839286,  5.52946429,  6.07589286,  3.87053571,  3.91071429,
        6.8125    ,  4.03392857,  1.55803571,  2.34910714,  3.69642857,
        4.34464286,  7.89196429,  6.57589286,  5.40267857,  5.97