In [1]:
import pandas as pd
import numpy as np
from statsmodels.stats.proportion import proportion_confint, samplesize_confint_proportion
import matplotlib.pyplot as plt
import scipy as sp

In [2]:
alpha = 0.003
c = np.round(sp.stats.norm.ppf(1 - alpha / 2) , 4)
print (c)

2.9677


In [3]:
sp.stats.norm()

In [4]:
use_aspirin = 11037
use_placebo = 11034
death_aspirin = 104
death_placebo = 189
p = (death_placebo/use_placebo)-(death_aspirin/use_aspirin)
print((death_placebo/use_placebo)-(death_aspirin/use_aspirin))

0.0077060239760047815


In [5]:
conv_int_aspirin = proportion_confint(death_aspirin,use_aspirin)

In [6]:
conv_int_placebo = proportion_confint(death_placebo,use_placebo)

In [7]:
conv_int_ratio = (conv_int_placebo[0] - conv_int_aspirin[0],conv_int_placebo[1] - conv_int_aspirin[1])

In [8]:
conv_int_ratio

(0.007087454468077034, 0.00832459348393253)

In [9]:
def conf_int():
    z = sp.stats.norm.ppf(0.975)
    return (a - z*np.sqrt(p*(1-p)),a + z*np.sqrt(p*(1-p)))

In [10]:
conf_int()

NameError: name 'a' is not defined

In [11]:
aspirin = np.full(use_aspirin, 0)
aspirin[np.arange(death_aspirin)] = 1
placebo = np.full(use_placebo, 0)
placebo[np.arange(death_placebo)] = 1

In [12]:
def proportions_confint_diff_ind(sample1, sample2, alpha = 0.05):    
    z = sp.stats.norm.ppf(1 - alpha / 2.)   
    p1 = float(sum(sample1)) / len(sample1)
    p2 = float(sum(sample2)) / len(sample2)
    
    odds_asp = dead_asp / (n_asp - dead_asp)
    odds_plac = dead_plac / (n_plac - dead_plac)
    odds_ratio = np.round(odds_plac / odds_asp, 4)
    return (left_boundary, right_boundary)

In [13]:
print("confidence interval: [%f, %f]" % proportions_confint_diff_ind(placebo, aspirin))

confidence interval: [0.004700, 0.010700]


In [14]:
0.0174 / (death_aspirin / (use_aspirin - death_aspirin))

1.829175

In [124]:
def get_bootstrap_samples(data, n_samples):
    indices = np.random.randint(0, len(data), (n_samples, len(data)))
    samples = data[indices]
    return samples
def stat_procesing(sample1, sample2):    
    len_asp = len(sample1[0])
    len_plac = len(sample2[0])
    dead_asp = np.sum(sample1,axis = 1)
    dead_plac = np.sum(sample2,axis = 1)
    
    odds_asp = dead_asp / (len_asp - dead_asp)
    odds_plac = dead_plac / (len_plac - dead_plac)
    odds_ratio = np.round(odds_plac / odds_asp, 4)
    return (odds_asp,odds_plac)

In [125]:
asp_group = get_bootstrap_samples(aspirin,1000)
plac_group = get_bootstrap_samples(placebo,1000)

In [126]:
b_count = 1000
np.random.seed(0)

placebo_odds = np.array(list(map(get_odds, get_bootstrap_samples(placebo, b_count))))
aspirin_odds = np.array(list(map(get_odds, get_bootstrap_samples(aspirin, b_count))))

In [136]:
sample = stat_procesing(asp_group,plac_group)
sample[1].sum()

17.465689922164923

In [137]:
placebo_odds.sum()

17.424091077166786

In [139]:
stat_intervals(sample[1] / sample[0], 0.05)

array([1.44187207, 2.36075051])

In [142]:
def proportions_confint_diff_ind(sample, alpha = 0.05):    
    z = sp.stats.norm.ppf(1 - alpha / 2.)   
    mean = sample.mean()  
    left_boundary = (mean) - z * sample.std() / np.sqrt(len(sample))
    right_boundary = (mean) + z * sample.std() / np.sqrt(len(sample))
    return (left_boundary, right_boundary)


In [143]:
proportions_confint_diff_ind(sample[1] / sample[0])

(1.8425715542111223, 1.8711832120731202)

In [87]:
asp_group.shape

(1000, 11037)

In [65]:
def get_bootstrap_samples(data, n_samples):
    indices = np.random.randint(0, len(data), (n_samples, len(data)))
    samples = data[indices]
    return samples
def stat_intervals(stat, alpha):
    boundaries = np.percentile(stat, [100 * alpha / 2., 100 * (1 - alpha / 2.)])
    boundaries = np.round(boundaries, 4)
    return boundaries
def get_odds(data):
    summ = data.sum() 
    n = len(data)  
    odds_ratio = summ / (n - summ)
    return odds_ratio

In [74]:
b_count = 1000
np.random.seed(0)

placebo_odds = np.array(list(map(get_odds, get_bootstrap_samples(placebo, b_count))))
aspirin_odds = np.array(list(map(get_odds, get_bootstrap_samples(aspirin, b_count))))

print("95% confidence interval for placebo_odds",  stat_intervals(placebo_odds, 0.05))
print("95% confidence interval for aspirin_odds",  stat_intervals(aspirin_odds, 0.05))
print("95% confidence interval for placebo_odds - aspirin_odds",  stat_intervals(placebo_odds / aspirin_odds, 0.05))

95% confidence interval for placebo_odds [0.0148 0.0199]
95% confidence interval for aspirin_odds [0.0078 0.0113]
95% confidence interval for placebo_odds - aspirin_odds [1.4629 2.3509]


In [90]:
placebo_odds

array([0.01808452, 0.01742739, 0.01761505, 0.01695853, 0.01836641,
       0.01977819, 0.01714602, 0.01714602, 0.01893065, 0.01761505,
       0.01883657, 0.01761505, 0.01977819, 0.01808452, 0.01658375,
       0.01752121, 0.01714602, 0.01686481, 0.01705226, 0.01902475,
       0.01752121, 0.01808452, 0.01780279, 0.01611566, 0.01574151,
       0.0167711 , 0.01752121, 0.01789668, 0.01911887, 0.01940133,
       0.01686481, 0.01836641, 0.01789668, 0.01836641, 0.01770891,
       0.01780279, 0.01742739, 0.01574151, 0.01827243, 0.01883657,
       0.01705226, 0.01977819, 0.0167711 , 0.01667742, 0.01705226,
       0.01827243, 0.0187425 , 0.0167711 , 0.01695853, 0.01799059,
       0.01714602, 0.01752121, 0.01770891, 0.01686481, 0.01667742,
       0.02176127, 0.01949552, 0.01742739, 0.01536763, 0.01686481,
       0.01639646, 0.0187425 , 0.01480732, 0.01883657, 0.01723979,
       0.01705226, 0.01714602, 0.01761505, 0.01949552, 0.01667742,
       0.01620925, 0.0160221 , 0.01611566, 0.01742739, 0.01733

In [91]:
aspirin_odds

array([0.00858997, 0.00905101, 0.00794521, 0.00886654, 0.00812934,
       0.00997438, 0.00831354, 0.00969719, 0.00942016, 0.00942016,
       0.00794521, 0.00849781, 0.00895877, 0.01043669, 0.00905101,
       0.00877434, 0.01015925, 0.00923555, 0.00960483, 0.00858997,
       0.00914328, 0.00914328, 0.00914328, 0.00960483, 0.0103442 ,
       0.00877434, 0.00877434, 0.00978957, 0.00895877, 0.01080685,
       0.00812934, 0.01062174, 0.00849781, 0.0113626 , 0.00895877,
       0.00978957, 0.00997438, 0.00988197, 0.00932785, 0.00858997,
       0.01043669, 0.00886654, 0.00895877, 0.00951249, 0.01015925,
       0.00858997, 0.01043669, 0.00840566, 0.00822143, 0.00905101,
       0.00942016, 0.01089943, 0.01071429, 0.00868214, 0.00905101,
       0.00997438, 0.00905101, 0.00840566, 0.00960483, 0.00942016,
       0.00932785, 0.00757714, 0.00868214, 0.00822143, 0.00877434,
       0.00822143, 0.00923555, 0.01043669, 0.00840566, 0.01117728,
       0.00923555, 0.00932785, 0.00942016, 0.00978957, 0.01034

In [92]:
placebo_odds / aspirin_odds

array([2.10530717, 1.92546209, 2.21706679, 1.91264193, 2.2592742 ,
       1.98289949, 2.06242099, 1.76814264, 2.0095895 , 1.86993174,
       2.37080906, 2.07289377, 2.20768984, 1.73278232, 1.83225288,
       1.99687039, 1.68772423, 1.82607434, 1.77538417, 2.21476432,
       1.91629473, 1.97790367, 1.94709067, 1.67787089, 1.52177196,
       1.91138154, 1.99687039, 1.82813739, 2.13409503, 1.79528073,
       2.07456052, 1.72913371, 2.106035  , 1.61639177, 1.97671188,
       1.81854624, 1.74721535, 1.59295314, 1.95891147, 2.19285672,
       1.63387603, 2.23065343, 1.87203149, 1.7532134 , 1.67849571,
       2.12718244, 1.79582728, 1.99521427, 2.06272197, 1.98768756,
       1.82014134, 1.6075342 , 1.65283158, 1.9424705 , 1.84260182,
       2.18171747, 2.15395944, 2.07329064, 1.59998948, 1.79028911,
       1.75779726, 2.47355816, 1.70549163, 2.2911542 , 1.96479729,
       2.07412358, 1.85652326, 1.68780004, 2.31933101, 1.49208197,
       1.75509229, 1.71766331, 1.71076383, 1.78019933, 1.67568

In [78]:
np.percentile(placebo_odds, [100 * alpha / 2., 100 * (1 - alpha / 2.)])

array([0.01480732, 0.0198748 ])

In [77]:
alpha = 0.05

In [79]:
placebo_odds

array([0.01808452, 0.01742739, 0.01761505, 0.01695853, 0.01836641,
       0.01977819, 0.01714602, 0.01714602, 0.01893065, 0.01761505,
       0.01883657, 0.01761505, 0.01977819, 0.01808452, 0.01658375,
       0.01752121, 0.01714602, 0.01686481, 0.01705226, 0.01902475,
       0.01752121, 0.01808452, 0.01780279, 0.01611566, 0.01574151,
       0.0167711 , 0.01752121, 0.01789668, 0.01911887, 0.01940133,
       0.01686481, 0.01836641, 0.01789668, 0.01836641, 0.01770891,
       0.01780279, 0.01742739, 0.01574151, 0.01827243, 0.01883657,
       0.01705226, 0.01977819, 0.0167711 , 0.01667742, 0.01705226,
       0.01827243, 0.0187425 , 0.0167711 , 0.01695853, 0.01799059,
       0.01714602, 0.01752121, 0.01770891, 0.01686481, 0.01667742,
       0.02176127, 0.01949552, 0.01742739, 0.01536763, 0.01686481,
       0.01639646, 0.0187425 , 0.01480732, 0.01883657, 0.01723979,
       0.01705226, 0.01714602, 0.01761505, 0.01949552, 0.01667742,
       0.01620925, 0.0160221 , 0.01611566, 0.01742739, 0.01733

In [80]:
def get_bootstrap_samples(data, n_samples):
    indices = np.random.randint(0, len(data), (n_samples, len(data)))
    samples = data[indices]
    return samples
def stat_intervals(stat, alpha):
    boundaries = np.percentile(stat, [100 * alpha / 2., 100 * (1 - alpha / 2.)])
    boundaries = np.round(boundaries, 4)
    return boundaries
def get_odds(data):
    summ = data.sum() 
    n = len(data)  
    odds_ratio = summ / (n - summ)
    return odds_ratio

In [81]:
b_count = 1000
np.random.seed(0)

placebo_odds = np.array(list(map(get_odds, get_bootstrap_samples(placebo, b_count))))
aspirin_odds = np.array(list(map(get_odds, get_bootstrap_samples(aspirin, b_count))))

print("95% confidence interval for placebo_odds",  stat_intervals(placebo_odds, 0.05))
print("95% confidence interval for aspirin_odds",  stat_intervals(aspirin_odds, 0.05))
print("95% confidence interval for placebo_odds - aspirin_odds",  stat_intervals(placebo_odds / aspirin_odds, 0.05))

95% confidence interval for placebo_odds [0.0148 0.0199]
95% confidence interval for aspirin_odds [0.0078 0.0113]
95% confidence interval for placebo_odds - aspirin_odds [1.4629 2.3509]


In [112]:
def odds(data):
    p = data.sum() / data.shape[0]
    return p / (1 - p)

In [113]:
np.random.seed(0)
aspirin_data = np.array( [1 if i<104 else 0 for i in range(11037)] )
placebo_data = np.array( [1 if i<189 else 0 for i in range(11034)] )
odds_aspirin = odds(aspirin_data)
print('Odds aspirin: %.4f' % odds_aspirin)
odds_placebo = odds(placebo_data)
print('Odds aspirin: %.4f' % odds_placebo)

Odds aspirin: 0.0095
Odds aspirin: 0.0174


In [114]:
def get_bootstrap_samples(data, n_samples):
    indices = np.random.randint(0, len(data), (n_samples, len(data)))
    samples = data[indices]
    return samples

In [115]:
def stat_intervals(stat, alpha):
    boundaries = np.percentile(stat, [100 * alpha / 2., 100 * (1 - alpha / 2.)])
    return boundaries

In [116]:
np.random.seed(0)
odds_aspirin_data = np.array(map(odds, get_bootstrap_samples(aspirin_data, 1000)))
odds_placebo_data = np.array(map(odds, get_bootstrap_samples(placebo_data, 1000)))

In [117]:

print('95%% confidence interval for times decrease of infarction: %s' %
      str(stat_intervals(odds_placebo_data / odds_aspirin_data, 0.05)))

TypeError: unsupported operand type(s) for /: 'map' and 'map'